import Footer from "@/components/Footer";
import Header from "@/components/Header";
import "@/styles/globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark, neobrutalism, shadesOfPurple } from "@clerk/themes";
import { Provider } from "react-redux";
import store from "@/store/store";
import Head from "next/head";

import { Analytics } from "@vercel/analytics/react"
import { SpeedInsights } from "@vercel/speed-insights/next"

export default function App({ Component, pageProps }) {
  return <>

    <Head>
      <title>Online Game Store | Gaming Hill</title>
      <meta
        name="description"
        content="Generated by create next app"
      />
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1"
      />
      <link rel="icon" href="/Gaming Hill.ico" />
      <link rel="preconnect" href="https://fonts.googleapis.com" />
      <link
        rel="preconnect"
        href="https://fonts.gstatic.com"
        crossOrigin="true"
      />
      <link
        href="https://fonts.googleapis.com/css2?family=Oswald:wght@200;300;400;500;600;700&family=Urbanist:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap"
        rel="stylesheet"
      />
    </Head>

    <ClerkProvider
      appearance={{
        layout: {
          socialButtonsPlacement: 'top',
          socialButtonsVariant: 'auto',
          termsPageUrl: 'https://clerk.com/terms',
          privacyPageUrl: "https://clerk.com/privacy",
          // logoImageUrl: 'https://img.freepik.com/free-vector/bird-colorful-logo-gradient-vector_343694-1365.jpg?size=338&ext=jpg&ga=GA1.1.1395880969.1710115200&semt=sph'
          // logoImageUrl: 'Enter Your Customized ImageUrl',
          showOptionalFields: true,
        }
      }}
      {...pageProps}>
      <Provider store={store}>
        <Header />
        <Component {...pageProps} />;
        <Analytics/>
        <SpeedInsights/>
        <Footer />
      </Provider>
    </ClerkProvider>
  </>

}
